# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-10-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stud_marks',
            options={'verbose_name': 'Student Mark', 'verbose_name_plural': 'Student Marks'},
        ),
        migrations.AddField(
            model_name='stud_info',
            name='s_contact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='stud_info',
            name='s_address',
            field=models.CharField(max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='stud_info',
            name='s_name',
            field=models.CharField(max_length=264, unique=True, verbose_name='Name'),
        ),
    ]
