# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-10-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20211001_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_marks',
            name='s_marks1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Django'),
        ),
        migrations.AlterField(
            model_name='stud_marks',
            name='s_marks2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Programming in R'),
        ),
        migrations.AlterField(
            model_name='stud_marks',
            name='s_marks3',
            field=models.IntegerField(blank=True, null=True, verbose_name='IONIC'),
        ),
    ]
