# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-11-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20211002_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_info',
            name='s_address',
            field=models.CharField(max_length=200, verbose_name='Student Address'),
        ),
        migrations.AlterField(
            model_name='stud_info',
            name='s_name',
            field=models.CharField(max_length=264, unique=True, verbose_name='Student Name'),
        ),
    ]
