# Generated by Django 4.0 on 2022-02-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20211117_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='stud_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stud_marks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
