# Generated by Django 4.0 on 2022-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_studentimage_alter_stud_info_id_alter_stud_marks_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=200, null=True)),
                ('StudentId', models.CharField(max_length=50, null=True)),
                ('LecturesAttended', models.IntegerField(null=True)),
                ('TotalLectures', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=200, null=True)),
                ('StudentId', models.CharField(max_length=50, null=True)),
                ('PhysicsMarks', models.IntegerField(null=True)),
                ('ChemistryMarks', models.IntegerField(null=True)),
                ('MathsMarks', models.IntegerField(null=True)),
                ('EnglishMarks', models.IntegerField(null=True)),
                ('ComputerMarks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
